### ISSUE TITLE
Minimize used Pins

### ISSUE THREAD

**Issue by derFrickler** [Bodmer/TFT_ILI9341_ESP#1]
Hi, Thanks a lot for this great library! 

Just one Question. As the esp has a limited number of pins, is it possible to use only 4 pins for driving the display? 
MISO and RESET are not needed in all cases as far as i know, if i see it right, i can set Reset to -1 to not use it.
Right now i am using the adafruit lib on 4 Pins TFT_CS, TFT_DC, TFT_MOSI, TFT_CLK.
As it uses softSPI, i chose D5-D8 on the ESP. Would this be possible with your lib too? 
I guess as you use hardware SPI, it it not possible to reuse the MISO pin (D6) for DC?

Thanks 
          Johannes

**Comment by Bodmer** [comment]
Hi Johannes,

 

Yes, you can connect the display reset pin to the NodeMCU RST pin and set TFT_RST to -1

 

The TFT has a software reset so I ought to add that at some point.

 

MISO (D6) is not needed though I have just added a readcommand (due to popular demand) which would use that pin if called.  I have tried to use D6 (MISO) as the DC line but the sketch but the display stays blank so the SPI library is possibly forcing it to be an input.

 

The library uses hardware SPI for speed so I have not tried Software SPI and I think it almost certainly will not work as low level SPI register access is used. It is something to add but I am trying to make small steps and test things as I go along.

 

Regards,

Bodmer

**Comment by derFrickler** [comment]
Thanks a lot for your answer! Yes, i tried it as well without success. 
Had some problems with DC on D0 or A0, now with D4 it works just fine!
Thanks a lot for your work.

**Comment by Bodmer** [comment]
I think the NoceMCU A0 and D0 (GPIO16) pins behave slightly differently due to the underlying system hardware and software that runs in the background but I have not investigated this.

D4 and D5 labels on some NodeMCU boards are incorrectly swapped so this can cause grief too.

**Comment by derFrickler** [comment]
Thanks again for the lib! D4 and D5 worked just fine for DC. 
Just to bad that the ESP has so less pins available... 
Using all of them right now in my last project - including rx/tx...

http://der-frickler.net/_media/modellbau/esp/envmon/envmon_001.jpg

**Comment by Bodmer** [comment]
Nice project, the display looks great.  It is nice to see a project that gets boxed up properly too!
