### ISSUE TITLE
drawBitmap

### ISSUE THREAD

**Issue by Franciscopcosta** [Bodmer/TFT_ILI9341_ESP#3]
i am having issues with drawBitmap function, is it working ok?

**Comment by Bodmer** [comment]
Hi, can you post an  example sketch that illustrates the problem.?

The TFT_eSPI library replaces this one so it may be worth trying that newer library.

**Comment by Franciscopcosta** [comment]
i used this page: **_http://www.rinkydinkelectronics.com/_t_doimageconverter565.php_**
to convert an image with 244x97 pixels, copied the array to **TFT_Flash_Bitmap** example, change this function parameter:
`drawIcon(logo_blocks_244x97, 0, 0, 244, 97);`
but its not working... it flashs some garbage on screen, and nothing more...

(i also tried with new library)

**Comment by Bodmer** [comment]
OK, I"ll set up a test later today and see what is happening, I suspect it may be the byte order in the image file.  Thanks for reporting this.

**Comment by Franciscopcosta** [comment]
if i use smaller image like 40x45 it shows ok....  but larger ones, it doesnt.
do you recommend any online converter?

**Comment by Bodmer** [comment]
Hi, the problem is that I used int8_t for the width and height parameters, so 244 looks like a negative number.  Correct the function prototype as shown here in bold to read:

void drawIcon(const unsigned short* icon, int16_t x, int16_t y, **uint16_t** width, **uint16_t** height)
{
  .... no changes needed to code
}

**Comment by Franciscopcosta** [comment]
@Bodmer it worked! thank you very much!
